sudo: required
language: go
go:
- 1.9.2
services:
- docker

install:
- docker pull therecipe/qt:windows_64_static
- docker pull therecipe/qt:linux
- go get -u -v github.com/therecipe/qt/cmd/...
- go get github.com/skratchdot/open-golang/open

script:
- $GOPATH/bin/qtdeploy -docker build windows_64_static
- $GOPATH/bin/qtdeploy -docker build linux
